"""0004 add AuthorModel.deleted

Revision ID: d148b9c28bf6
Revises: dc94f66410dc
Create Date: 2026-09-20 16:10:21.263227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd148b9c28bf6'
down_revision = 'dc94f66410dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), server_default='False', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
