"""0007 delete QuoteModel.is_deleted

Revision ID: d1932cb8b594
Revises: 099bffc9d5f2
Create Date: 2026-09-20 17:55:15.369093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1932cb8b594'
down_revision = '099bffc9d5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), server_default=sa.text("'False'"), nullable=False))

    # ### end Alembic commands ###
